### ISSUE TITLE
Support for Israel(Tel Aviv) Region "il-central-1"

### ISSUE THREAD

**Issue by veltz-avi** [aws-solutions/application-monitoring-with-amazon-cloudwatch#36]
The solution deployment is failing in Israel(Tel Aviv) Region "il-central-1"
Version: 1.2.4
Released: 10/2023

**Additional context**
Embedded stack arn:aws:cloudformation:il-central-1:500236090997:stack/tlv-Application-Monitoring-with-Amazon-CloudWatch-NginxStack-1U7NQRRFNIOP8/a03f9300-a26d-11ee-9217-0a713dc645fe was not successfully created: The following resource(s) failed to create: [TagHandlerE89DBFCE, DashboardHandler5DC2C81F, HelperD4411AF3].

![Screenshot 2023-12-24 at 17 06 53](https://github.com/aws-solutions/application-monitoring-with-amazon-cloudwatch/assets/68636084/b46247c2-a135-4465-afef-e91456d17f25)

**Comment by abe-aws** [comment]
Thanks for this report. We will add support for this region in a future release.
